appId: com.example.flutter_lv
---
# ASSUMES USER IS LOGGED IN

- waitForAnimationToEnd

- tapOn:
    text: "Settings"

- waitForAnimationToEnd

- assertVisible:
    text: "Settings"

- takeScreenshot: "06_settings_screen"